-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ 
  START WITH 10 -- 1부터 생성(기본값:1)
  INCREMENT BY -1 -- 1씩 증가(기본값)
  MAXVALUE 9999 -- 최대값
  MINVALUE -9999 -- 최소값
  NOCYCLE       
  NOCACHE;      -- 캐시메모리를 사용 안 함
SELECT FRIEND_SQ.NEXTVAL FROM DUAL; -- NEXTVAL(순차번호생성), DUAL:오라클 제공 테이블(1행1열)
SELECT FRIEND_SQ.CURRVAL FROM DUAL; -- CURRVAL(현재까지 진행된 순차번호)

-- ex. 시퀀스를 이용한 FRIEND테이블 
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
  NO   NUMBER(5) PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL,
  TEL  VARCHAR2(20) UNIQUE,
  ADDRESS VARCHAR2(255),
  LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS) 
  VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '신림'); -- 여러번 실행 가능
SELECT NO, NAME, TEL, ADDRESS, 
    TO_CHAR(LAST_MODIFY, 'RR/MM/DD AM HH:MI:SS') LAST_MODIFY
  FROM FRIEND;
  
  
  
  DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MEMBER_LEVEL CASCADE CONSTRAINTS;
DROP SEQUENCE MEMBER_MNO_SQ;


  
  CREATE TABLE MEMBER_LEVEL (
    LEVELNO NUMBER PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL
);

CREATE TABLE MEMBER (
    mNO NUMBER PRIMARY KEY,
    mNAME VARCHAR2(20) NOT NULL,
    mPW VARCHAR2(8) CHECK (LENGTH(mPW) BETWEEN 1 AND 8),
    mEMAIL VARCHAR2(50) UNIQUE,
    mPOINT NUMBER CHECK (mPOINT >= 0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER,
    CONSTRAINT FK_MEMBER_LEVEL
        FOREIGN KEY (LEVELNO)
        REFERENCES MEMBER_LEVEL(LEVELNO)
);

CREATE SEQUENCE MEMBER_MNO_SQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0,  '일반');
INSERT INTO MEMBER_LEVEL VALUES (1,  '실버');
INSERT INTO MEMBER_LEVEL VALUES (2,  '골드');


INSERT INTO MEMBER
VALUES (
    MEMBER_MNO_SQ.NEXTVAL,   
    '홍길동',               
    'aa',                   
    'hong@hong.com',        
    0,                     
    DATE '2022-03-10',     
    0                       
);

INSERT INTO MEMBER
VALUES (
    MEMBER_MNO_SQ.NEXTVAL,
    '신길동',
    'bb',
    'sin@sin.com',
    1000,
    DATE '2022-04-01',
    1
);


SELECT 
    m.mNO,
    m.mNAME,
    TO_CHAR(m.mRDATE, 'YYYY-MM-DD') AS 가입일,
    m.mEMAIL,
    m.mPOINT,
    CASE 
        WHEN l.LEVELNO = -1 THEN 'black회원'
        WHEN l.LEVELNO = 0 THEN '일반고객'
        WHEN l.LEVELNO = 1 THEN '실버고객'
        WHEN l.LEVELNO = 2 THEN '골드고객'
    END AS LEVELNAME
FROM MEMBER m
JOIN MEMBER_LEVEL l
    ON m.LEVELNO = l.LEVELNO
ORDER BY m.mNO;